version: '3.8'

services:

  server:
    image: hmes98318/logistics-node:1.0.0
    container_name: logistics-node
    restart: always
    ports:
      - 7000:7000
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7000
      - DEPOT=/data/depot
      - MONGO_URL=mongodb://logistics:dbpAssw0rd@db:27017/
      - DATABASE_NAME=depot
      - DATABASE_COLLECTION=list
      - KEY_LENGTH=5
      - MAX_LISTENING=10
    volumes:
      - /usr/local/logistics-node/depot:/data/depot
    depends_on:
      - db
    networks:
      - logistics-net

  db:
    image: mongo
    container_name: logistics-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=logistics
      - MONGO_INITDB_ROOT_PASSWORD=dbpAssw0rd
    volumes:
      - /usr/local/logistics-node/data/db:/data/db
    networks:
      - logistics-net

networks:
  logistics-net: